version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - mkdir lib
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip p1.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://code-buckets-assign-3/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name assignment-3-lambda --s3-bucket code-buckets-assign-3 -builds-zip --s3-key deployment_package.zip
      - echo "Deployment complete!"
